---
title: "Aapa distribution map of Norway"
format: html
---


```{r setup}
library(tidyverse)
#library(dbConnect)
library(dbplyr)
library(DBI)
library(RPostgres)
library(stars)
library(sf)
```


```{r connectionObject}
# the password is stored in a pgpass.conf file
con <- DBI::dbConnect(drv = RPostgres::Postgres(), host = "t2lippgsql03", dbname = "ano_moduler")
```


```{r getData}
bc <- dplyr::tbl(con, dbplyr::in_schema("helper_variables", "bioclimatic_regions"))

bc <- bc |>
  mutate(geom_wkb = dbplyr::sql("ST_AsBinary(geom)")) |>
  select(-geom) |>
  collect() |>
  mutate(geom = sf::st_as_sfc(geom_wkb, crs = 25833)) |>
  sf::st_as_sf(sf_column_name = "geom")

```


```{r define}
reg <- unique(bc$BCregion)
# we exclude boreonemoral and south boreal sones (6SO1-2 and 6SE1)
exl <- grep("6SO-1-2|6SE-1", reg)

# 1 = presence; 0 = absence
bc2 <- bc |>
  mutate(aapa = case_when(
    BCregion %in% reg[exl] ~ 0,
    .default = 1
  ))

# test:
bc2 |> as_tibble() |> count(aapa)

bc2 |>
  slice_sample(prop = 0.2) |>
  tmap::tm_shape() +
  tmap::tm_fill(col = "aapa", style = "cat")

```

```{r checkResolution}
temp <- bc2 |>
    mutate(km2 = units::drop_units(st_area(geom))*10^-6)

summary(temp |> as_tibble() |> pull(km2))
# area is 1 km1
```

```{r importGrid}
grid <- readRDS("data/grid50_kyst_bgr.rds")
dplyr_summary <- function(data, var) {
  if (inherits(data, "sf")) {
    data <- sf::st_drop_geometry(data)
  }
  data %>%
    summarise(
      Min    = min({{ var }}, na.rm = TRUE),
      Q1     = quantile({{ var }}, 0.25, na.rm = TRUE),
      Median = median({{ var }}, na.rm = TRUE),
      Mean   = mean({{ var }}, na.rm = TRUE),
      Q3     = quantile({{ var }}, 0.75, na.rm = TRUE),
      Max    = max({{ var }}, na.rm = TRUE)
    )
}

grid |>
  mutate(km2 = units::drop_units(st_area(geometry))*10^-6) |>
  dplyr_summary(km2)

# the area varies
```

```{r rasterizeGrid}

grid_raster <- st_rasterize(grid)

# the area of each pixle should be should 100 km2
temp <- grid_raster |>
    st_as_sf() |>
    mutate(km2 = units::drop_units(st_area(geometry))*10^-6)

summary(temp |> as_tibble() |> pull(km2))
# it is not
```

```{r rasterize}
bc_raster <- st_rasterize(bc2) 
#bc_raster_grid <- st_rasterize(bc2, grid_raster, align = TRUE) 
plot(bc_raster)
#plot(bc_raster_grid)

st_crs(bc_raster) # UTM  - OK
```


```{r aggregate}
bc_raster10 <- st_warp(
  bc_raster,
  cellsize = 10000,
  method = "max",
  use_gdal = TRUE
)
plot(bc_raster10)
```


```{r test}
# the area of each pixle should be should 100 km2
temp <- bc_raster10 |>
    st_as_sf() |>
    mutate(km2 = units::drop_units(st_area(geometry))*10^-6)

summary(temp |> as_tibble() |> pull(km2))
# OK
```


```{r export}
saveRDS(bc_raster10, "output/aapa_dist_map.rds")
write_stars(bc_raster10, "output/aapa_dist_map.tif")

# export fines scale raster
saveRDS(bc_raster, "output/aapa_dist_map_1km2.rds")
write_stars(bc_raster, "output/aapa_dist_map_1km2.tif")


saveRDS(bc2, "output/aapa_dist_map_1km2_vector.rds")
```